module.exports = {
  ARTIST_INPUT_FIELD_CHARACTER_LIMIT_FORMATTED: 100,
  CHANNEL_NAME_INPUT_FIELD_CHARACTER_LIMIT: 30,
  FEATURES_INPUT_FIELD_CHARACTER_LIMIT: 30,
  ARTIST_INPUT_FIELD_CHARACTER_LIMIT: 30,
  TITLE_INPUT_FIELD_CHARACTER_LIMIT: 45,
};
